### ISSUE TITLE
[REQUEST] Showcase token variations 

### ISSUE THREAD

**Issue by DoParkEQ** [EQWorks/react-labs#104]
## Is your feature request related to a problem?

Currently, both typography and shadow show its variations one at a time. I'd like to add a section that shows all token variations.

---
## Are you able to assist bring the feature to reality?

👌
---

**Comment by SamSverko** [comment]
What are "token variations"?

**Comment by DoParkEQ** [comment]
Tokens refer to design element forms look and feel of UI components. Typefaces, colors and shadows are examples of that. I am thinking of adding a section that shows all variations at once just like the `colors` page.
