### ISSUE TITLE
isPercentage adds % to all rows in DataTable and DynamicDataTable 

### ISSUE THREAD

**Issue by tlowande** [EQWorks/react-labs#17]
https://github.com/EQWorks/react-labs/blob/b5bab03bf36961c7b7392f5b71c0b6a4004c20dd/src/data-table.js#L75

`isPercentage` adds % to all rows in `DataTable` and `DynamicDataTable` when `true`

**Comment by woozyking** [comment]
this is where https://github.com/EQWorks/react-labs/pull/6 came from, and where i then introduced https://github.com/EQWorks/extended-semantic-components/tree/master/src/data-table which has per-column config

this is not a bug that can be fixed through the current way how columns are configured. but ^ can be a reference implementation to be ported over for a more comprehensive and generic data table solution
