### ISSUE TITLE
[BUG] Button | colours get too dark when used as a link

### ISSUE THREAD

**Issue by SamSverko** [EQWorks/react-labs#93]
## Describe the bug

> feedback from using dynamic button + href attribute: the button gets super dark when you attach an href attribute. It already gets dark when you hover on it (and then gets darker b/c of the href attribute)

---

## To Reproduce

---

## Expected behavior

Button styling when used as a link should be the same as if it were not used as a link.

---

#### How it looks without hovering
![Screen Shot 2020-08-17 at 8 04 11 PM](https://user-images.githubusercontent.com/42495034/90455733-d598e380-e0c4-11ea-9885-b9f0fb3fdd0b.png)

#### With my current workaround of hardcoding what color is shown upon hover:
![Screen Shot 2020-08-17 at 8 07 19 PM](https://user-images.githubusercontent.com/42495034/90455892-450ed300-e0c5-11ea-9e79-a99f1791f421.png)

#### Without my current workaround upon hover
![Screen Shot 2020-08-17 at 8 05 53 PM](https://user-images.githubusercontent.com/42495034/90455819-109b1700-e0c5-11ea-81b9-7dfcab41569c.png)

---

## Code snippets

When I use DynamicButton like this, I get a super dark button
```jsx
DynamicButton
          className={classes.button}
          href={`${url}/hub/login?stage=${stage}&jwt=${jwt}`}
          target='_blank'
          rel='noopener noreferrer'
          startIcon={<LibraryBooksIcon />}
          type='primary'
          size='large'
 >
```
However, when I remove the href, it gets dark but its still easy to view (as intended)

---

## System

- **OS:** [e.g. `Windows 10`, `macOS Catalina 10.15.6`]
- **Browser:** [e.g. `chrome`, `safari`, `firefox`]
- **Version:** [e.g. `1.5`]
- **Relevant Dependency Version:** [e.g. `@storybook/react@5.3.18`]

---

## Additional context

How I've been able to work around it is by putting in CSS styling on the button like this:
```css
button: {
    backgroundColor: '#0075FF',
    color: 'white',
    '&:hover': { color: 'white', backgroundColor: '#236abf' },
  },
```

**Comment by DoParkEQ** [comment]
```backgroundImage: `linear-gradient(0deg, ${theme.palette.action.active}, ${theme.palette.action.active})`,```

I found that it is due to `backgroundImage` uses `theme.palette.action.active`. Switching it to `theme.palette.action.hover` would resolve the issue. The same behaviour is noticed from `StyledRadio`.

@SamSverko I can fix this issue after your latest PR is merged.
