### ISSUE TITLE
[REQUEST] Add color palettes examples

### ISSUE THREAD

**Issue by DoParkEQ** [EQWorks/react-labs#95]
## Is your feature request related to a problem?

![Screen Shot 2020-08-20 at 5 07 00 PM](https://user-images.githubusercontent.com/59836949/90825895-95757300-e307-11ea-96bf-562a9258ad37.png)

`Colors` is one of the design elements for our UI. Right now we only have examples for `Typography` and `Shadows` in Storybook.

---

## Describe the solution you'd like

I'd like to add color palettes examples under `System`

---

## Are you able to assist bring the feature to reality?

Yes. I'll implement this myself to get familiar with storybook 6.0 and added features/recent changes in react-labs

**Comment by SamSverko** [comment]
Love this!!
